# Base compose file for Values Match backend
# Only defines stuff that is the same, both in development and production.
#
# For development it will automatically be use together with docker-compose.override.yml which defines
# volumes to be mounted.
# cmd: docker-compose up -d --build
#
# For production it will be used together with docker-compose.production.yml which defines environment variables
# and extra logging services.
# cmd: docker-compose -f docker-compose.yml -f docker-compose.production.yml


version: '3'
services:
  api:
    command: "npm run dev"
    volumes:
      - "./api/src:/app/src"

  client:
    command: "npm run dev"
    volumes:
      - "./client/src:/app/src"
