# Base compose file for Rebus
# Only defines stuff that is the same, both in development and production.
#
# For development it will automatically be use together with docker-compose.override.yml which defines
# volumes to be mounted.
# cmd: docker-compose up -d --build
#
# For production it will be used together with docker-compose.production.yml which defines environment variables
# and extra logging services.
# cmd: docker-compose -f docker-compose.yml -f docker-compose.production.yml


version: '3'
services:
  api:
    image: rebus/api
    build: ./api/.
    ports:
      - 3000:3000


  client:
    image: rebus/client
    build: client/.
    ports:
      - 3000:3000 # maybe this should be on another port?
      - 35729:35729

  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
