version: '3'
services:
  api:
    command: "npm run dev"
    environment:
      - MONGO_URL=mongodb://mongo/rebus
      - PORT=3000
      - EXTERNAL_PORT=3000
      - EXTERNAL_HOST=api
    volumes:
      - "./api/src:/app/src"

  client:
    environment:
      - GRAPHQL_HTTP_ENDPOINT=http://api:3000/graphql
      - GRAPHQL_WS_ENDPOINT=ws://api:3000/subscriptions
    volumes:
      - "./client:/app"
